// utils/truckData.ts
import { Truck } from '@/types/trucks';
import truckphoto from '@/public/iveco-removebg-preview.png';

export const mockTrucks: any[] = [
  { 
    id: 1, 
    plate: '154 TN 2457', 
    driver: 'Michael Johnson', 
    driverFr: 'Michael Johnson',
    odometer: 458900,
    fuelType: 'Diesel',
    lastMaintenance: '2023-11-20',
    model: 'Freightliner Cascadia',
    status: 'active',
    purchaseDate: '2020-03-15',
    capacity: 500,
    revenue: 45000, 
    diesel: 2500,
    photo: '/iveco-removebg-preview.png',
    monthlyDieselData: [
      { month: 'Jan', consumption: 3200 },
      { month: 'Feb', consumption: 2800 },
      { month: 'Mar', consumption: 3500 },
      { month: 'Apr', consumption: 2900 },
      { month: 'May', consumption: 3100 },
      { month: 'Jun', consumption: 3400 },
      { month: 'Jul', consumption: 3600 },
      { month: 'Aug', consumption: 3300 },
      { month: 'Sep', consumption: 3800 },
      { month: 'Oct', consumption: 3900 },
      { month: 'Nov', consumption: 4100 },
      { month: 'Dec', consumption: 4300 },
    ],
    monthlyRevenueData: [
      { month: 'Jan', revenue: 12500 },
      { month: 'Feb', revenue: 13200 },
      { month: 'Mar', revenue: 14100 },
      { month: 'Apr', revenue: 12900 },
      { month: 'May', revenue: 13500 },
      { month: 'Jun', revenue: 14200 },
      { month: 'Jul', revenue: 14800 },
      { month: 'Aug', revenue: 13900 },
      { month: 'Sep', revenue: 15100 },
      { month: 'Oct', revenue: 15500 },
      { month: 'Nov', revenue: 16000 },
      { month: 'Dec', revenue: 16500 },
    ],
    trips: [
      { date: '2024-03-20', product: 'Sand 4/8', productFr: 'Sable 4/8', quantity: 25, destination: 'City Center', destinationFr: 'Centre-ville', status: 'Invoiced', statusFr: 'Facturé', revenue: 1250.00 },
      { date: '2024-03-18', product: 'Gravel 20', productFr: 'Gravier 20', quantity: 28, destination: 'Industrial Park', destinationFr: 'Parc industriel', status: 'Invoiced', statusFr: 'Facturé', revenue: 1400.00 },
      { date: '2024-03-15', product: 'Aggregates', productFr: 'Granulats', quantity: 30, destination: 'Construction Site A', destinationFr: 'Chantier A', status: 'Pending', statusFr: 'En attente', revenue: 1500.00 },
      { date: '2024-03-12', product: 'Soil', productFr: 'Terre', quantity: 22, destination: 'Residential Area', destinationFr: 'Zone résidentielle', status: 'Invoiced', statusFr: 'Facturé', revenue: 1100.00 },
      { date: '2024-03-10', product: 'Sand 4/12', productFr: 'Sable 4/12', quantity: 26, destination: 'City Docks', destinationFr: 'Quais de la ville', status: 'Invoiced', statusFr: 'Facturé', revenue: 1300.00 },
      { date: '2024-03-20', product: 'Sand 4/8', productFr: 'Sable 4/8', quantity: 25, destination: 'City Center', destinationFr: 'Centre-ville', status: 'Invoiced', statusFr: 'Facturé', revenue: 1250.00 },
      { date: '2024-03-18', product: 'Gravel 20', productFr: 'Gravier 20', quantity: 28, destination: 'Industrial Park', destinationFr: 'Parc industriel', status: 'Invoiced', statusFr: 'Facturé', revenue: 1400.00 },
      { date: '2024-03-15', product: 'Aggregates', productFr: 'Granulats', quantity: 30, destination: 'Construction Site A', destinationFr: 'Chantier A', status: 'Pending', statusFr: 'En attente', revenue: 1500.00 },
      { date: '2024-03-12', product: 'Soil', productFr: 'Terre', quantity: 22, destination: 'Residential Area', destinationFr: 'Zone résidentielle', status: 'Invoiced', statusFr: 'Facturé', revenue: 1100.00 },
      { date: '2024-03-10', product: 'Sand 4/12', productFr: 'Sable 4/12', quantity: 26, destination: 'City Docks', destinationFr: 'Quais de la ville', status: 'Invoiced', statusFr: 'Facturé', revenue: 1300.00 },
    ],
    repairs: [
      { id: 1, date: '2024-02-15', type: 'Engine Repair', typeFr: 'Réparation moteur', cost: 1200, notes: 'Replaced fuel injectors', notesFr: 'Injecteurs de carburant remplacés', status: 'completed' },
      { id: 2, date: '2024-01-20', type: 'Brake System', typeFr: 'Système de freinage', cost: 850, notes: 'Replaced brake pads and rotors', notesFr: 'Plaquettes et disques de frein remplacés', status: 'completed' },
      { id: 3, date: '2023-12-10', type: 'Transmission', typeFr: 'Transmission', cost: 2100, notes: 'Transmission overhaul', notesFr: 'Révision complète de la transmission', status: 'completed' },
      { id: 4, date: '2023-11-20', type: 'Regular Maintenance', typeFr: 'Maintenance régulière', cost: 450, notes: 'Oil change, filter replacement', notesFr: 'Changement d\'huile, remplacement du filtre', status: 'completed' },
      { id: 5, date: '2024-03-05', type: 'Suspension', typeFr: 'Suspension', cost: 750, notes: 'Pending parts delivery', notesFr: 'En attente de livraison des pièces', status: 'pending' },
      { id: 1, date: '2024-02-15', type: 'Engine Repair', typeFr: 'Réparation moteur', cost: 1200, notes: 'Replaced fuel injectors', notesFr: 'Injecteurs de carburant remplacés', status: 'completed' },
      { id: 2, date: '2024-01-20', type: 'Brake System', typeFr: 'Système de freinage', cost: 850, notes: 'Replaced brake pads and rotors', notesFr: 'Plaquettes et disques de frein remplacés', status: 'completed' },
      { id: 3, date: '2023-12-10', type: 'Transmission', typeFr: 'Transmission', cost: 2100, notes: 'Transmission overhaul', notesFr: 'Révision complète de la transmission', status: 'completed' },
      { id: 4, date: '2023-11-20', type: 'Regular Maintenance', typeFr: 'Maintenance régulière', cost: 450, notes: 'Oil change, filter replacement', notesFr: 'Changement d\'huile, remplacement du filtre', status: 'completed' },
      { id: 5, date: '2024-03-05', type: 'Suspension', typeFr: 'Suspension', cost: 750, notes: 'Pending parts delivery', notesFr: 'En attente de livraison des pièces', status: 'pending' },
    ]
  },
];
